### ISSUE TITLE
Review CONTRIBUTING.md and make sure everything make sense

### ISSUE THREAD

**Issue by ChrisDinhNZ** [ChrisDinhNZ/MultilinksCore#17]
CONTRIBUTING.md was recently added as a guide for contributing to the project. This is still marked draft and ideally it would be nice to have someone review it.

Once reviewed and everything is good to go, remove (draft) from the heading and make a pull request.

**Comment by pBouillon** [comment]
Hey ! I can handle this one if it is still open !

**Comment by ChrisDinhNZ** [comment]
Yep sure
